# Terragon Autonomous SDLC Configuration
# Adaptive value discovery and continuous improvement system

metadata:
  repository: "tokamak-rl-control-suite"
  maturity_level: "developing"  # nascent/developing/maturing/advanced
  last_assessment: "2025-01-15T10:30:00Z"
  assessment_version: "1.0"

scoring:
  # Adaptive weights based on repository maturity level
  weights:
    nascent:
      wsjf: 0.4
      ice: 0.3
      technical_debt: 0.2
      security: 0.1
    developing:
      wsjf: 0.5
      ice: 0.2
      technical_debt: 0.2  
      security: 0.1
    maturing:
      wsjf: 0.6
      ice: 0.1
      technical_debt: 0.2
      security: 0.1
    advanced:
      wsjf: 0.5
      ice: 0.1
      technical_debt: 0.3
      security: 0.1

  # Score thresholds and multipliers
  thresholds:
    min_composite_score: 10
    max_risk_tolerance: 0.8
    security_boost_multiplier: 2.0
    compliance_boost_multiplier: 1.8
    dependency_update_penalty: 0.8
    documentation_penalty: 0.6

discovery:
  # Signal sources for value discovery
  sources:
    - git_history       # TODOs, FIXMEs, commit patterns
    - static_analysis   # Code quality metrics
    - issue_trackers    # GitHub/GitLab issues
    - vulnerability_db  # CVE, security advisories
    - performance_data  # Profiling, benchmarks
    - user_feedback     # Support tickets, reviews

  # Analysis tools configuration
  tools:
    static_analysis:
      - ruff            # Python linting
      - mypy            # Type checking
      - bandit          # Security analysis
      - sonarqube       # Code quality (optional)
    
    security:
      - pip_audit       # Python dependency scanning
      - safety          # Security vulnerabilities
      - semgrep         # Static security analysis
      - trivy           # Container scanning (future)
    
    performance:
      - pytest_benchmark # Performance regression testing
      - memory_profiler  # Memory usage analysis
      - py_spy          # CPU profiling (optional)

execution:
  # Autonomous execution parameters
  max_concurrent_tasks: 1
  execution_schedule:
    immediate: "on_pr_merge"
    hourly: "security_scan"
    daily: "comprehensive_analysis"
    weekly: "deep_assessment"
    monthly: "strategic_review"

  # Quality gates
  quality_requirements:
    min_test_coverage: 80
    max_performance_regression: 5  # percent
    security_vulnerability_tolerance: "low"
    
  # Rollback triggers
  rollback_conditions:
    - test_failure
    - build_failure
    - security_violation
    - performance_degradation

monitoring:
  # Value tracking metrics
  metrics:
    velocity:
      - cycle_time_hours
      - items_completed_per_week
      - backlog_growth_rate
    
    quality:
      - test_coverage_percent
      - code_quality_score
      - technical_debt_ratio
      - security_posture_score
    
    business_value:
      - feature_completion_rate
      - bug_resolution_time
      - performance_improvement_percent
      - user_satisfaction_score

  # Alert thresholds
  alerts:
    high_technical_debt: 0.4      # debt ratio > 40%
    low_test_coverage: 70         # coverage < 70%
    security_vulnerability: "any" # any security issue
    performance_regression: 10    # > 10% slower

learning:
  # Continuous learning and adaptation
  feedback_loops:
    - prediction_accuracy_tracking
    - effort_estimation_calibration
    - impact_measurement_validation
    - scoring_model_refinement
  
  # Model adaptation parameters
  adaptation:
    confidence_adjustment_threshold: 0.2
    effort_estimation_tolerance: 0.3
    impact_prediction_variance: 0.25
    learning_rate: 0.1

# Repository-specific context
context:
  domain: "fusion-energy-ml"
  primary_language: "python"
  frameworks: ["gymnasium", "stable-baselines3", "pytorch"]
  deployment_target: "research"
  safety_criticality: "high"  # plasma control safety
  
  # Business priorities
  priorities:
    - physics_accuracy: "critical"
    - safety_systems: "critical" 
    - performance: "high"
    - documentation: "medium"
    - user_experience: "medium"

# Current SDLC maturity assessment
maturity_assessment:
  current_score: 45  # out of 100
  category: "developing"
  
  strengths:
    - comprehensive_documentation
    - well_structured_project
    - quality_tooling_setup
    - clear_contribution_guidelines
  
  gaps:
    - missing_ci_cd_workflows
    - limited_test_coverage  
    - no_automated_security_scanning
    - absent_performance_monitoring
  
  next_improvements:
    - implement_ci_cd_automation
    - expand_test_suite_coverage
    - add_security_scanning_integration
    - setup_performance_benchmarking
    - establish_value_tracking_system