{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "tokamak-rl-data",
    "namespace": "tokamak-rl"
  },
  "spec": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "resources": {
      "requests": {
        "storage": "10Gi"
      }
    },
    "storageClassName": "fast-ssd"
  }
}