{
  "apiVersion": "v1",
  "kind": "ConfigMap",
  "metadata": {
    "name": "prometheus-config",
    "namespace": "tokamak-rl"
  },
  "data": {
    "prometheus.yml": "{\n  \"global\": {\n    \"scrape_interval\": \"15s\",\n    \"evaluation_interval\": \"15s\"\n  },\n  \"scrape_configs\": [\n    {\n      \"job_name\": \"tokamak-rl\",\n      \"kubernetes_sd_configs\": [\n        {\n          \"role\": \"pod\",\n          \"namespaces\": {\n            \"names\": [\n              \"tokamak-rl\"\n            ]\n          }\n        }\n      ],\n      \"relabel_configs\": [\n        {\n          \"source_labels\": [\n            \"__meta_kubernetes_pod_annotation_prometheus_io_scrape\"\n          ],\n          \"action\": \"keep\",\n          \"regex\": \"true\"\n        },\n        {\n          \"source_labels\": [\n            \"__meta_kubernetes_pod_annotation_prometheus_io_path\"\n          ],\n          \"action\": \"replace\",\n          \"target_label\": \"__metrics_path__\",\n          \"regex\": \"(.+)\"\n        }\n      ]\n    }\n  ]\n}"
  }
}